/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL,
  PRIMARY KEY (id)
);

ALTER TABLE animals
ADD COLUMN species VARCHAR(100);

CREATE TABLE owners (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(100),
  age INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE species (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  PRIMARY KEY (id)
);

ALTER TABLE animals 
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INTEGER,
ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id)
ON DELETE CASCADE;

ALTER TABLE animals
ADD COLUMN owner_id INTEGER,
ADD CONSTRAINT fk_owners FOREIGN KEY (owner_id) REFERENCES owners(id)
ON DELETE CASCADE;


-- new table
CREATE TABLE vets (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  age INTEGER,
  date_of_graduation DATE,
  PRIMARY KEY (id)
);

CREATE TABLE specializations (
  vet_id INTEGER,
  species_id INTEGER,
  PRIMARY KEY (vet_id, species_id),
  FOREIGN KEY (vet_id) REFERENCES vets(id)
  ON DELETE CASCADE,
  FOREIGN KEY (species_id) REFERENCES species(id)
  ON DELETE CASCADE
);

CREATE TABLE visits (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  animal_id INTEGER,
  vet_id INTEGER,
  date_of_visit DATE,
  PRIMARY KEY (id),
  FOREIGN KEY (animal_id) REFERENCES animals(id)
  ON DELETE CASCADE,
  FOREIGN KEY (vet_id) REFERENCES vets(id)
  ON DELETE CASCADE
);