/* Database schema to keep the structure of entire database. */
DROP TABLE IF EXISTS animals;

CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL,
  PRIMARY KEY (id)
);

ALTER TABLE animals
ADD COLUMN species VARCHAR(100);
